#!/bin/bash
# Инструкция по добавлению доменов ETM в V2Box

echo "=== Добавление доменов ETM в V2Box ==="
echo ""
echo "1. Открой V2Box приложение"
echo "2. Перейди в Settings → Routing"
echo "3. Найди секцию Domain Rules или Direct/Proxy Rules"
echo "4. Добавь следующие домены в список для проксирования:"
echo "   - etm.ru"
echo "   - ipro.etm.ru"
echo ""
echo "5. Сохрани изменения и перезапусти соединение"
echo ""
echo "Текущие домены в V2Box должны включать:"
echo "  ✓ ozon.ru"
echo "  ✓ wildberries.ru"
echo "  ✓ googleapis.com"
echo "  ✓ feron.ru"
echo "  ✓ russvet.ru"
echo "  + etm.ru (ДОБАВИТЬ)"
echo "  + ipro.etm.ru (ДОБАВИТЬ)"
echo ""
echo "После добавления запусти тест:"
echo "cd ~/Code/Checksheets_Project/Checksheets && python3 test_connectivity.py"
